services:
    # strapi:
    #     image: ghcr.io/iotechpis/tearfil-render-api:release
    #     restart: always
    #     env_file:
    #         - .env
    #     ports:
    #         - 59967:1337
    #     networks:
    #         - tearfil_render
    #     volumes:
    #         - strapi_uploads:/usr/src/app/public/uploads
    #     healthcheck:
    #         test: ["CMD", "node", "-e", "require('http').get('http://localhost:1337/_health', (res) => { process.exit(res.statusCode === 200 || res.statusCode === 204 ? 0 : 1) }).on('error', () => process.exit(1))"]
    #         interval: 30s
    #         timeout: 10s
    #         retries: 5
    #     depends_on:
    #         mysql:
    #             condition: service_healthy
    #             restart: true

    mysql:
      image: mysql:8
      restart: always
      ports:
        - "59966:3306"
      networks:
        - tearfil_render
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 15s
        timeout: 30s
        retries: 60
      environment:
        TZ: ${TZ}
        PUID: ${PUID}
        MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
        MYSQL_DATABASE: ${DATABASE_NAME}
        MYSQL_USER: ${DATABASE_USERNAME}
        MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      volumes:
        - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
    # strapi_uploads:

networks:
    tearfil_render:
